### PR TITLE
support for cleaning entity storage

### PR DESCRIPTION
**Pull request by sebastianburckhardt**
Add support for cleaning empty entities and releasing orphaned entity locks.

Addresses the issues discussed in #1325 and #1065.

### CODE REVIEW

**Comment by cgillum** [comment]
I suggest adding some automated tests to verify the correct behavior for these changes.

**Review by cgillum — APPROVED** [review]
LGTM! - :shipit:

**Comment by cgillum** [comment]
@sebastianburckhardt glad to see this merged! Would you mind creating a docs PR to add information about this and perhaps a code sample to the [entities documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities)?

Also @davidmrdavid can you open work items in our JS and Python repos to track support for this in JS and Python respectively?

**Comment by sebastianburckhardt** [comment]
I think the tests that were added with this PR are causing spurious build failures. The reason is that they are susceptible to other tests leaving empty entities in storage. I will need to fix this.

**Comment by cgillum** [comment]
ok - FYI @bachuv on the test flakiness since I noticed one of your PRs had test failures.

**Pull request merged**
