### PR TITLE
Add DFPerfScenarios test project

### PR DESCRIPTION
**Pull request by cgillum**
This PR adds the performance testing project that we use for validating extension releases.

### CODE REVIEW

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Hi! I have received your command: `run ManySequences count=5000`

I've started a new deployment orchestration with ID **DFTestBot-PR1464-20200908055435** that will validate the changes in this PR. If the build succeeds, the orchestration will create an app named **dftest-ManySequences-pr1464-20200908-a19c** and run the **ManySequences** test using your custom build.
I'll report back when I have status updates.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Hi! I have received your command: `run ManySequences count=5000`

I've started a new deployment orchestration with ID **DFTestBot-PR1464-20200908063428** that will validate the changes in this PR. If the build succeeds, the orchestration will create an app named **dftest-ManySequences-pr1464-20200908-8aa3** and run the **ManySequences** test using your custom build.
I'll report back when I have status updates.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

The test was terminated or timed out. ⚠

You can view more detailed results in [AppLens](https://applens.azurewebsites.net/subscriptions/92d757cd-ef0d-4710-967d-2efa3c952358/resourceGroups/perf-testing/providers/Microsoft.Web/sites/dftest-ManySequences-pr1464-20200908-8aa3/detectors/DurableFunctions_ManySequencesTest?startTime=2020-09-08T06:34&endTime=2020-09-08T03:03) (Microsoft internal). 🔗📈

The test app **dftest-ManySequences-pr1464-20200908-8aa3** will be deleted at 2020-09-08 04:03:56 UTC.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Hi! I have received your command: `run ManySequences count=100`

I've started a new deployment orchestration with ID **DFTestBot-PR1464-20200908030701** that will validate the changes in this PR. If the build succeeds, the orchestration will create an app named **dftest-ManySequences-pr1464-20200908-5e7e** and run the **ManySequences** test using your custom build.
I'll report back when I have status updates.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

All 100 HelloSequence sequences have completed. Succeeded: **100**. Failed: **0**.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

The test completed successfully! ✅

You can view more detailed results in [AppLens](https://applens.azurewebsites.net/subscriptions/92d757cd-ef0d-4710-967d-2efa3c952358/resourceGroups/perf-testing/providers/Microsoft.Web/sites/dftest-ManySequences-pr1464-20200908-5e7e/detectors/DurableFunctions_ManySequencesTest?startTime=2020-09-08T03:07&endTime=2020-09-08T03:10) (Microsoft internal). 🔗📈

The test app **dftest-ManySequences-pr1464-20200908-5e7e** will be deleted at 2020-09-08 04:10:06 UTC.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

The syntax for commands is: `/DFTest run <TestName> <Param1> <Param2> ...`

Here are the supported `<TestName>` values:

* `ManySequences`: Runs `count` "Hello cities" sequencial orchestrations in parallel. Example: `/DFTest run ManySequences count=10000`.
* `FanOutFanIn`: Runs a single orchestration that fans out to `count` number of activity functions. Example: `/DFTest run FanOutFanIn count=10000`. **(DISABLED)**

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Here are the supported `<TestName>` values:

* `ManySequences`: Runs `count` "Hello cities" sequencial orchestrations in parallel. Example: `/DFTest run ManySequences count=10000`.
* `FanOutFanIn`: Runs a single orchestration that fans out to `count` number of activity functions. Example: `/DFTest run FanOutFanIn count=10000`. **(DISABLED)**

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Hi! I have received your command: `run ManySequences count=10000`.
* `FanOutFanIn`: Runs a single orchestration that fans out to `count` number of activity functions. Example: `/DFTest run FanOutFanIn count=10000`. **(DISABLED)**
`

I've started a new deployment orchestration with ID **DFTestBot-PR1464-20200908045945** that will validate the changes in this PR. If the build succeeds, the orchestration will create an app named **dftest-ManySequences-pr1464-20200908-e5a7** and run the **ManySequences** test using your custom build.
I'll report back when I have status updates.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Hi! I have received your command: `run FanOutFanIn count=10000`. **(DISABLED)**
`

I've started a new deployment orchestration with ID **DFTestBot-PR1464-20200908045945** that will validate the changes in this PR. If the build succeeds, the orchestration will create an app named **dftest-ManySequences-pr1464-20200908-e5a7** and run the **ManySequences** test using your custom build.
I'll report back when I have status updates.
`

I've started a new deployment orchestration with ID **DFTestBot-PR1464-20200908045951** that will validate the changes in this PR. If the build succeeds, the orchestration will create an app named **dftest-FanOutFanIn-pr1464-20200908-2ab9** and run the **FanOutFanIn** test using your custom build.
I'll report back when I have status updates.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Failed to deploy the test app! 💣 Check the internal deployment service logs for more details.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

An unexpected failure occurred! 💣 Unfortunately, we can't continue the test run and the test app will be deleted. 😞

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Failed to deploy the test app! 💣 Check the internal deployment service logs for more details.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

An unexpected failure occurred! 💣 Unfortunately, we can't continue the test run and the test app will be deleted. 😞

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

Hi! I have received your command: `run ManySequences count=100`

I've started a new deployment orchestration with ID **DFTestBot-PR1464-20200908060000** that will validate the changes in this PR. If the build succeeds, the orchestration will create an app named **dftest-ManySequences-pr1464-20200908-657a** and run the _ManySequences_ test using your custom build.

I'll report back when I have status updates.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

All 100 HelloSequence sequences have completed. Succeeded: **100**. Failed: **0**.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

The test completed successfully! ✅

You can view more detailed results in [AppLens](https://applens.azurewebsites.net/subscriptions/92d757cd-ef0d-4710-967d-2efa3c952358/resourceGroups/perf-testing/providers/Microsoft.Web/sites/dftest-ManySequences-pr1464-20200908-657a/detectors/DurableFunctions_ManySequencesTest?startTime=2020-09-08T06:00&endTime=2020-09-08T06:03) (Microsoft internal). 🔗📈

The test app **dftest-ManySequences-pr1464-20200908-657a** will be deleted at 2020-09-08 07:03:12 UTC.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

The test app dftest-ManySequences-pr1464-20200908-657a has been deleted. Thanks for using the DFTest bot!

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

The syntax for commands is: `/DFTest run <TestName> <Param1> <Param2> ...`

Here are the supported `<TestName>` values:

* `ManySequences`: Runs `count` "Hello cities" sequencial orchestrations in parallel. Example: `/DFTest run ManySequences count=10000`.
* `FanOutFanIn`: Runs a single orchestration that fans out to `count` number of activity functions. Example: `/DFTest run FanOutFanIn count=10000`. **(DISABLED)**

**Comment by cgillum** [comment]
.
.
.
.
.
.
.
.
. (whitespace - ignore)
.
.
.
.
.
.
.

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

The syntax for commands is: `/DFTest run <TestName> <Param1> <Param2> ...`

Here are the supported `<TestName>` values:

* `ManySequences`: Runs `count` "Hello cities" sequencial orchestrations in parallel. Example: `/DFTest run ManySequences count=10000`.
* `FanOutFanIn`: Runs a single orchestration that fans out to `count` number of activity functions. Example: `/DFTest run FanOutFanIn count=10000`. **(DISABLED)**

**Comment by cgillum** [comment]
🤖**Durable Functions Test Bot**🤖

The syntax for commands is: `/DFTest run <TestName> <Param1> <Param2> ...`

Here are the supported `<TestName>` values:

* `ManySequences`: Runs `count` "Hello cities" sequencial orchestrations in parallel. Example: `/DFTest run ManySequences count=10000`.
* `FanOutFanIn`: Runs a single orchestration that fans out to `count` number of activity functions. Example: `/DFTest run FanOutFanIn count=10000`. **(DISABLED)**

**Comment by ConnorMcMahon** [comment]
@cgillum, I konw this was for a test, but do you think this is something we may want to get into the repo. It doesn't make much of a difference to me how we track this issue, just wanted to follow up since it is currently in 2.3.1 milestone.

**Comment by cgillum** [comment]
@ConnorMcMahon yeah, let's go ahead and merge this (pending a sign-off). It's long overdue that we get some of this test code into the repo. It will be useful for the work @bachuv is doing with the test bot anyways.

**Pull request merged**
