### PR TITLE
Adding support for source-link

### PR DESCRIPTION
**Pull request by gled4er**
Hello @cgillum,

May I ask you to take a look on this first commit for adding support for source-link as described in https://github.com/Azure/azure-functions-durable-extension/issues/526?

Thank you!

### CODE REVIEW

**Comment by cgillum** [comment]
Is this the only change that is required? Would you be able to somehow demonstrate that it is working as expected, maybe with screenshots? I'm not actually familiar with how to set it up, but I assumed there was more to it.

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you for the comment.

Great idea about the testing!

I will continue to work on it and update you about the progress.

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

I was able to achieve the expected result with integrating source-link.

Please check the following images:









May I ask you to review the changes and let me know what should be fixed next?

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you for the great feedback!

Yes, it makes perfect sense.

The best way to test it against .Net Framework is to modify the host.json or you suggest other option?

Thank you!

**Comment by cgillum** [comment]
I think all you need to do is create a function app which targets Functions 1.0, clear your nuget cache, and make sure that customers can still manually set breakpoints and break into Durable Functions code. If source-link works, that's great to, but not required.

I think targeting 1.0 is as simple as updating the .csproj file (you may also need to make updates to host.json). When you reference your local build of the nuget package, it will target the right framework automatically.

**Comment by cgillum** [comment]
According to this Twitter thread, it might be expected to work on all versions of .NET: https://twitter.com/kirillosenkov/status/1007052524946255872?lang=en

I'll try to test it as well.

**Comment by gled4er** [comment]
Great!

Thank you!

I will try it soon.

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

I was able to test and verify that source-link works for .NET Framework as well as you can see from the images below:









In the last commit you will see a small change in `DurableTaskExtensions.Initialize` method. The problems is that `this.nameResolver` is null when we execute against **.Net Framework** and the host is not able to start. The regression was introduced from the change we made for setting `TaskHub` name from the `local.settings.json` in https://github.com/Azure/azure-functions-durable-extension/pull/503/files#diff-8e71038a95b35db07c2b23ecbc95b728R150 And the fix I added is:

```csharp
            if (this.nameResolver != null &&
                this.nameResolver.TryResolveWholeString(this.Options.HubName, out string taskHubName))
            {
                // use the resolved task hub name
                this.Options.HubName = taskHubName;
            }
```
 I was able to detect the error partially thanks to the new source-link feature.

Let me know if you prefer to make the correction in the way presented above or you prefer to have 

```csharp
#if NETSTANDARD2_0
           if (this.nameResolver.TryResolveWholeString(this.Options.HubName, out string taskHubName))
            {
                // use the resolved task hub name
                this.Options.HubName = taskHubName;
            }
#endif
```

Thank you!

**Comment by cgillum** [comment]
Thanks Kanio for making that additional fix. It's good that we did some manual testing to detect this regression.

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you  for the quick response that allowed us add the correct fix immediately!

Thank you!

**Pull request merged**
