### PR TITLE
Remove JS samples

### PR DESCRIPTION
**Pull request by davidmrdavid**
This PR aims to remove the JS samples directory from this repo, to avoid the duplication of effort of maintaining samples here and in the DF JS repo.

Before merging this, we need to remove all references to these JS samples in our docs. That PR is here: https://github.com/MicrosoftDocs/azure-docs-pr/pull/206664

### CODE REVIEW

**Comment by cgillum** [comment]
Do we have any pointer in this repo to let JS users know where to find the official JS samples?

**Comment by davidmrdavid** [comment]
@cgillum: not really. We do have the DF JS repo linked in the README, but that's about it.
What kind of note where you thinking we could use to point users to the right samples?

**Comment by cgillum** [comment]
A note (or a table) in the README is good enough for me.

**Comment by cgillum** [comment]
@davidmrdavid gentle reminder about this open PR in case it may have fallen off the radar.

**Comment by davidmrdavid** [comment]
@cgillum: thanks for the ping. It had not fallen off my radar, but it was de-prioritized. Please let me know if the newly added note in the README fits your requirements.

**Review by cgillum — APPROVED** [review]
:shipit:

**Pull request merged**
