### PR TITLE
removing redundant setting

### PR DESCRIPTION
**Pull request by jeffhollan**
@kashimiz I don't think we need this value? I don't see it being accessed from any samples and adds some confusion especially when running without storage emulator

per feedback from @sdras

### CODE REVIEW

**Comment by sdras** [comment]
Thank you!

**Comment by cgillum** [comment]
I asked @kashimiz about this setting and apparently it was needed by one of the samples which [uses the Azure Storage SDK directly](https://github.com/Azure/azure-functions-durable-extension/blob/bd887fce280023445b112d82555a667d4d7b9a60/samples/javascript/E2_CopyFileToBlob/index.js#L3). Is that not the case?

**Comment by cgillum** [comment]
Yeah, I'd be cool with that change. The fewer config settings, the better. :)

**Comment by jeffhollan** [comment]
Closing in favor of this PR:

https://github.com/Azure/azure-functions-durable-extension/pull/480

**Pull request closed without merging**
