### PR TITLE
Promote dev to main for 2.7.2 DF Extension release

### PR DESCRIPTION
**Pull request by davidmrdavid**
As in title, routine PR

### CODE REVIEW

**Comment by cgillum** [comment]
I'll sign off on this after https://github.com/Azure/azure-functions-durable-extension/pull/2196 gets merged into dev.

**Comment by davidmrdavid** [comment]
@cgillum, the prophecy has been fulfilled - https://github.com/Azure/azure-functions-durable-extension/pull/2196
_the PR is merged_

**Review by cgillum — APPROVED** [review]

**Comment by sebastianburckhardt** [comment]
In the list of commits above, the fourth line (commit 3938c6a) says "In progress work -not yet functional". That sounds a bit alarming. Is this just an outdated commit description?

**Comment by davidmrdavid** [comment]
@sebastianburckhardt I believe that was part of a PR which didn't have its commits squashed...so I think we're seeing some PR's full history in there

**Comment by cgillum** [comment]
Yes, it looks like a non-squashed PR merge by me. 😓

**Comment by davidmrdavid** [comment]
no problemo. I mean, I deleted the `main` branch not too long ago, so worse git things have happened :P

**Comment by sebastianburckhardt** [comment]
The PR in question is https://github.com/Azure/azure-functions-durable-extension/pull/2185
(make sure to include it in the Release Notes)

**Pull request merged**
