### PR TITLE
Adding new Purging History API-s

### PR DESCRIPTION
**Pull request by gled4er**
Hello @cgillum,

This is PR for integrating the changes made in Durable Task project for the History Retention feature - https://github.com/Azure/azure-functions-durable-extension/issues/17.

When you have time, please take a look.

Thank you!

### CODE REVIEW

**Comment by gled4er** [comment]
Hello @cgillum,

I added integration tests for the new **Purge History API-s**.

May I ask you to take a look when you have time and let me know what should be fixed?

Thank you!

**Comment by cgillum** [comment]
Thanks! I'll take a look today.

**Comment by gled4er** [comment]
Thank you very much @cgillum!

**Comment by cgillum** [comment]
@gled4er would you mind opening a docs PR so we can document this feature? It will need to go into the [release-functions-durable-migration](https://github.com/MicrosoftDocs/azure-docs-pr/tree/release-functions-durable-migration) branch.

**Comment by gled4er** [comment]
Hello @cgillum,

Yes, I will.

Thank you for reminding me!

I think we will need documentation for the `DurableActivityContextBase` as well.

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

I opened this PR for the documentation - https://github.com/MicrosoftDocs/azure-docs-pr/pull/57364

Please review it when you have time.

Thank you!

**Pull request merged**
