### PR TITLE
Adding deserialization capabilities for DurableOrchestrationStatus' properties

### PR DESCRIPTION
**Pull request by gled4er**
Hello @cgillum,

I wanted to open this PR to frame the discussion for #388.

Please review when you have time.

Thank you!

### CODE REVIEW

**Comment by brandonh-msft** [comment]
Am I missing the part where we actually deserialize the status object in the tests? are we just relying on the internal passing between orchestrators/activities to be doing this and asserting it is correct?

**Comment by cgillum** [comment]
@brandonh-msft Correct. I think this is good enough validation since this is exactly the scenario we're trying to enable (passing the status object between functions).

Also, it looks like there were some test failures. @gled4er can you check and see if these failing tests are passing locally for you, and consistently? I wasn't expecting any test regressions from your change, so I'm curious to know if this is some kind of flakiness or some kind of existing issue.

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you for the message.

I will check the tests and let you know here.

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

I run locally all the integration tests that were failing locally and for me they are passing. I needed to rerun the **ActorOrchestration** twice to pass. But the rest were ok from the first attempt. I was running them individually after clearing everything from the Azure Emulator. 

I will run all test next but usually this take a lot of time and I will share the results here.

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

I run all the tests in my local environment  and all of them passed - in total 280.

Next, I will double check the code and try to commit something small that will trigger the CI again.

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

This time all the tests passed.

Let me know if something else is required to be fixed for this pull request.

Thank you!

**Pull request merged**
