### PR TITLE
Adding instructions for setting Storage Account

### PR DESCRIPTION
**Pull request by gled4er**
For me following the instructions did not work if I am not running the local storage emulator and set the connection string to it or storage account in Azure.

### CODE REVIEW

**Comment by cgillum** [comment]
Sorry for forgetting to add this. It should be set up this way in the sample project, but it definitely needs to be included in these instructions for folks who don't use the sample project. Thanks for taking the time to submit this doc fix!

**Comment by gled4er** [comment]
Sure. I really enjoythe documentation. It gives you a lot of useful information how Durable Functions work!

**Comment by arerlend** [comment]
@cgillum - I know this is an old issue, but would it be possible to improve the error message for when UseDevelopmentStorage=true and the storage emulator isn't running?

The error message below is a bit unintuitive, especially "The function 'E1_HelloSequence' doesn't exist... The following are the active orchestrator functions: ." in particular.  Just a nonessential QoL fix for DF newcomers that might prevent some frayed nerves. 

```
{
    "id": "...",
    "requestId": "...",
    "statusCode": 500,
    "errorCode": 0,
    "message": "Exception while executing function: HttpStart -> The function 'E1_HelloSequence' doesn't exist, is disabled, or is not an orchestrator function. The following are the active orchestrator functions: .",
    "errorDetails": "Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: HttpStart ---> System.ArgumentException : The function 'E1_HelloSequence' doesn't exist, is disabled, or is not an orchestrator function. The following are the active orchestrator functions: .\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.AssertOrchestratorExists(String name,String version)\r\n   at async Microsoft.Azure.WebJobs.DurableOrchestrationClient.StartNewAsync(??)\r\n   at CallSite.Target(Closure ,CallSite ,Object )\r\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site,T0 arg0)\r\n   at async VSSample.HttpStart.Run(HttpRequestMessage req,DurableOrchestrationClient starter,String functionName,TraceWriter log)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) \r\n   End of inner exception\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw()\r\n   at async Microsoft.Azure.WebJobs.JobHost.CallAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Script.ScriptHost.CallAsync(String method,Dictionary`2 arguments,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.HandleRequestAsync(FunctionDescriptor function,HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.Host.FunctionRequestInvoker.ProcessRequestAsync(HttpRequestMessage request,CancellationToken cancellationToken,WebScriptHostManager scriptHostManager,WebHookReceiverManager webHookReceiverManager)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.<>c__DisplayClass3_0.<ExecuteAsync>b__0(??)\r\n   at async Microsoft.Azure.WebJobs.Extensions.Http.HttpRequestManager.ProcessRequestAsync(HttpRequestMessage request,Func`3 processRequestHandler,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.ExecuteAsync(HttpControllerContext controllerContext,CancellationToken cancellationToken)\r\n   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.WebScriptHostHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.SystemTraceHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async System.Web.Http.HttpServer.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)"
}

**Comment by cgillum** [comment]
@arerlend that's a good idea - I get tripped up on this as well when testing. Would you mind opening a new issue to track this?

**Pull request merged**
