### PR TITLE
Downgraded dependencies to version 1.1.2

### PR DESCRIPTION
**Pull request by mlankamp**
Downgraded the dependencies for Microsoft.Extensions.Options and Microsoft.Extensions.Configuration.Abstractions to version 1.1.2 for net461 to prevent Newtonsoft.Json conflict in functionhost V1

### CODE REVIEW

**Comment by cgillum** [comment]
Thanks Michiel. I'm still seeing the same HTML updates and a commit history which includes other changes from August. Is your fork up-to-date?

**Comment by mlankamp** [comment]
I only have 1 commit in my pull request, and it only contains 1 changed file.

**Comment by cgillum** [comment]
This is what I'm seeing. Are you not seeing the same thing? And yes, it should go to **dev**.

image

**Comment by mlankamp** [comment]
Yes, I see the same thing. I'm going to give it a retry.

**Comment by cgillum** [comment]
I went ahead and fixed this with a new PR: #523

**Pull request closed without merging**
