### PR TITLE
Fix entity deserialization for class-based entities so it reflects custom serialization settings

### LINKED ISSUE #2361: SignalEntityAsync doesn't seem to leverage custom JsonSerializationSetings from custom IMessageSerializerSettingsFactory
### Description
I've got a durable entity defined in class scope that has properties with private setters.  When i call SingnalEntityAsync all these properties are set to default when the actual handle method is called.  If i add a [JsonProperty] to these properties with a private setter, their value is correct.

I tried setting a private resolver contract with
```
public class PrivateResolver : DefaultContractResolver
    {
        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            var prop = base.CreateProperty(member, memberSerialization);
            if (!prop.Writable)
            {
                var property = member as PropertyInfo;
                var hasPrivateSetter = property?.GetSetMethod(true) != null;
                prop.Writable = hasPrivateSetter;
            }
            return prop;
        }
    }

    internal class CustomMessageSerializerSettingsFactory : IMessageSerializerSettingsFactory
    {
        public JsonSerializerSettings CreateJsonSerializerSettings()
        {
            return new JsonSerializerSettings()
            {
                ContractResolver = new PrivateResolver(),
                TypeNameHandling = TypeNameHandling.None,
                DateParseHandling = DateParseHandling.None,
            };
        }
    }

 builder.Services.AddSingleton<IMessageSerializerSettingsFactory, CustomMessageSerializerSettingsFactory>();
```

i'm seeing my PrivateResolver::CreateProperty being called with the expected MemberInfos so DI seems configured right, but all SignalEntityAsync's from the DurableClient don't seem to set values for properties with private setters still.

### Expected behavior
Expect properties with private setters to have appropriate value 

### Actual behavior
value is set to default (null)

### Relevant source code snippets
see above

### Known workarounds
explicitly setting a [JsonProperty] attribute on each property and the value appears

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.9.1
- **Azure Functions runtime version (1.0 or 2.0)**: 4
- **Programming language used**: c#

### Screenshots
N/A

### If deployed to Azure
N/A

### PR DESCRIPTION
**Pull request by sebastianburckhardt**
### Issue describing the changes in this PR

resolves #2361 

### Pull request checklist

* [x] My changes **do not** require documentation changes
* [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
* [x] I have added all required tests (Unit tests, E2E tests)
* [x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
* [x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package

### CODE REVIEW

**Review by cgillum — APPROVED** [review]
Quick scan looks goot to me!

**Comment by cgillum** [comment]
The test failure looks interesting. Does this change impact the output of logging?

**Comment by sebastianburckhardt** [comment]
Since the only line that changed is in the code that deserializes class-based entities, I think it should affect only tests that contain such entities. From what I can see, none of the reported test failures contain any entities at all, so I think those test failures are not caused by this change. I am rerunning the tests now to see if the result changes.

**Comment by cgillum** [comment]
Looks like we're green. Merging...

**Pull request merged**
