### PR TITLE
Make durable client registration idempotent.

### LINKED ISSUE #2804: Orchestration Trigger input binding fails with "Orchestration history state was either missing from the input or not a string value"
### Description
Running into the uncaught exception `"Orchestration history state was either missing from the input or not a string value"`. 

Setup
1. Have two functions F1 and F2, the first is an HTTP trigger and the other is an orchestrator function
2. HTTP trigger F1 schedules a new orchestration instance for F2, and [adds an additional input object ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.durabletask.client.durabletaskclient.scheduleneworchestrationinstanceasync?view=durabletask-dotnet-1.x#microsoft-durabletask-client-durabletaskclient-scheduleneworchestrationinstanceasync(microsoft-durabletask-taskname-system-object-microsoft-durabletask-startorchestrationoptions-system-threading-cancellationtoken))
3. Before my debugger enters F2, the input binding fails:
```
[2024-04-26T21:46:38.116Z] An error occurred while executing the orchestrator function 'DispatchJob'.
[2024-04-26T21:46:38.117Z] Result: An error occurred while executing the orchestrator function 'DispatchJob'.
Exception: System.InvalidOperationException: Orchestration history state was either missing from the input or not a string value.
[2024-04-26T21:46:38.118Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.RunOrchestrationAsync(FunctionContext context, BindingMetadata triggerBinding, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 55
[2024-04-26T21:46:38.119Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
[2024-04-26T21:46:38.120Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.EnsureSynchronousExecution(FunctionContext functionContext, FunctionExecutionDelegate next, FunctionsOrchestrationContext orchestrationContext) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 81
[2024-04-26T21:46:38.121Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.RunAsync(TaskOrchestrationContext context, Object input) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 51Stack:    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.RunOrchestrationAsync(FunctionContext context, BindingMetadata triggerBinding, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 55
[2024-04-26T21:46:38.122Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
[2024-04-26T21:46:38.123Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.EnsureSynchronousExecution(FunctionContext functionContext, FunctionExecutionDelegate next, FunctionsOrchestrationContext orchestrationContext) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 81
[2024-04-26T21:46:38.124Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.RunAsync(TaskOrchestrationContext context, Object input) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 51.
[2024-04-26T21:46:38.676Z] Executed 'Functions.DispatchJob' (Failed, Id=56e78500-0d6f-4448-880e-47e1b1d9571a, Duration=7706ms)
[2024-04-26T21:46:38.678Z] System.Private.CoreLib: Exception while executing function: Functions.DispatchJob. Microsoft.Azure.WebJobs.Extensions.DurableTask: Orchestration history state was either missing from the input or not a string value.
[2024-04-26T21:46:38.681Z] c663be9b1bde4b788c83378174a3bb1c: Function 'DispatchJob (Orchestrator)' failed with an error. Reason: Orchestration history state was either missing from the input or not a string value.. IsReplay: False. State: Failed. RuntimeStatus: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.13.2. SequenceNumber: 5. TaskEventId: -1
```
4.  I debugged, and it seems the orchestration trigger input binding is somehow binding a full object rather than a string in here:
  a.. https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs#L49
  b. `triggerInputData` is expected to have a `.value` that is either null or string, but in my case it's a `{Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrationContext}`. The whole `triggerInputData` object after binding:
```
{
    "BindingMetadata": {
        "Name": "context",
        "Type": "orchestrationTrigger",
        "Direction": 0
    },
    "Value": {
        "IsAccessed": false,
        "Name": {
            "Name": "DispatchJob",
            "Version": ""
        },
        "InstanceId": "262ca4d6610f479da9e344d0681be433",
        "CurrentUtcDateTime": "2024-04-26T21:47:53.5989272Z",
        "IsReplaying": false,
        "Parent": null,
        "Entities": {}
    }
}
```

### Expected behavior
I expect the orchestration trigger to bind successfully, and start executing my function code.

### Actual behavior
`Function 'DispatchJob (Orchestrator)' failed with an error. Reason: Orchestration history state was either missing from the input or not a string value.`

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
I haven't encountered any workarounds yet.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: Microsoft.Azure.Functions.Worker.Extensions.DurableTask v 1.1.2
- **Azure Functions runtime version (1.0 or 2.0)**: V4,0
- **Programming language used**: C# ,NET 8 (isolated worker)

### Screenshots
image

### PR DESCRIPTION
**Pull request by jviau**
This PR addresses an issue where registering the durable worker extension twice would break the extension. The extension registration has now been made idempotent and safe to call multiple times. Additionally, durable extension registration has been made available in an extension method off `IFunctionsWorkerApplicationBuilder` to simplify cases where auto-registration via source gen is not available.

### Issue describing the changes in this PR

resolves #2804

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)
* [x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`
* [x] My changes **do not** add EventIds to our EventSource logs
    * [ ] Otherwise: Ensure the EventIds are within the supported range in our existing Windows infrastructure. You may validate this with a deployed app's telemetry. You may also extend the range by completing a PR such as [this one](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/7463263?_a=files).
* [ ] My changes **should** be added to v3.x branch.
    * [ ] Otherwise: This change only applies to Durable Functions v2.x and **will not** be merged to branch v3.x.

### CODE REVIEW

**Review by cgillum — COMMENTED** [review]
@jviau these changes look good to me. Can you comment on whether this has been tested? If so, I'd feel good about merging it.

**Comment by jviau** [comment]
@cgillum I have ran smoke tests and it succeeds. Also succeeds with a redundant call to `ConfigureDurableExtension` (added in this PR) to confirm it addresses the double-registration issue.

**Review by cgillum — APPROVED** [review]

**Comment by MarcinJuraszek** [comment]
Has this been released in any version already?

**Comment by cgillum** [comment]
@MarcinJuraszek yes, see the release notes here: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.2.0-worker-extension

**Pull request merged**
